base_config:
  - configs/base.yaml


max_batch_size: 1
model_cls: modules.model.unet_conform.midi_unet_conforms
task_cls: training.MIDIExtractionTask
binary_data_dir: data/some_ds_roundmidi_spk3_aug8/binary

num_valid_plots: 100
log_interval: 100
num_sanity_val_steps: 1  # steps of validation at the beginning
val_check_interval: 5000
num_ckpt_keep: 6
max_updates: 100000

midi_prob_deviation: 1.0
midi_shift_proportion: 0.0
midi_shift_range: [-12, 12]
rest_threshold: 0.1

midi_extractor_args:
  output_lay: 2
  dim: 512
  kernel_size: 31
  conv_drop:  0.1
  ffn_latent_drop: 0.1
  ffn_out_drop:  0.1
  attention_drop: 0.1
  attention_heads:  4
  attention_heads_dim: 64
  unet_type: 'cf_unet_full'
  unet_down: [2, 2, 2,2,2]
  unet_dim: [512, 512, 768,768,1024]
  unet_latentdim: 1024

pl_trainer_precision: 'bf16'
